# Generated by Django 4.1.5 on 2023-01-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_alter_voyage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
