# Generated by Django 4.1.5 on 2023-01-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_alter_voyage_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
