# Generated by Django 4.1.5 on 2023-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_alter_voyage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('ice', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('societe', models.CharField(max_length=100)),
                ('tel', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(default='Avion', max_length=100)),
            ],
        ),
    ]
