# Generated by Django 4.1.5 on 2023-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('ice', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('classification', models.CharField(default='5*', max_length=100)),
                ('tel', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('localisation', models.TextField()),
            ],
        ),
    ]
