# Generated by Django 4.1.5 on 2023-01-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='localisation',
            field=models.CharField(max_length=1000),
        ),
    ]
