# Generated by Django 4.1.5 on 2023-01-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0008_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyages.hotel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyages.transport'),
        ),
    ]
